# -*- coding: utf-8 -*-
"""Personal Task Assistant Crew Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZ0qskAnNvoRqqtKkszOc0bRcWyHX7YN
"""

# ============================================
# Minimal Personal Task Assistant Crew (Gemini + Serper) — CLEAN + WORKING
# ============================================
!pip install -qU crewai crewai-tools google-generativeai

import os, re
from datetime import datetime, timedelta
from crewai import Agent, Task, Crew, Process, LLM
from crewai_tools import SerperDevTool  # Valid BaseTool for CrewAI

# 1) Keys (set ONLY GOOGLE_API_KEY to avoid warnings)
os.environ["GOOGLE_API_KEY"] = "GOOGLE_API_KEY"  # https://ai.google.dev
os.environ["SERPER_API_KEY"] = "SERPER_API_KEY"  # https://serper.dev
os.environ.pop("GEMINI_API_KEY", None)  # silence: "Both GOOGLE_API_KEY and GEMINI_API_KEY are set"

# 2) LLM (Google Gemini)
llm = LLM(model="gemini/gemini-2.5-flash", temperature=0.6, api_key=os.environ["GOOGLE_API_KEY"])

# 3) Real web search tool (Serper)
web_search = SerperDevTool()  # reads SERPER_API_KEY from env

# 4) Agents
planner = Agent(
    role="🧠 Planner",
    goal="Break a goal into clear, ordered subtasks with dependencies.",
    backstory="You create concise, actionable study/work plans.",
    allow_delegation=False,
    verbose=False,
    llm=llm
)

executor = Agent(
    role="🧑‍💻 Executor",
    goal="Use tools to assemble a concrete schedule with dates, links, and time estimates.",
    backstory="You turn plans into day-by-day schedules with practical details.",
    tools=[web_search],  # Keep it simple: real search only
    allow_delegation=False,
    verbose=False,
    llm=llm
)

# 5) Helpers
def parse_days(goal: str, default=7) -> int:
    m = re.search(r'(\d+)\s*(day|days|d)\b', goal, re.I)
    return int(m.group(1)) if m else default

def date_list(days: int) -> str:
    today = datetime.now()
    return "\n".join(
        f"Day {i+1}: {(today + timedelta(days=i)).strftime('%Y-%m-%d (%A)')}"
        for i in range(days)
    )

# 6) Tasks (Planner → Executor via context)
def planning_task(goal: str) -> Task:
    return Task(
        description=f"""
        Goal: "{goal}"
        - Break into 6–10 subtasks in logical order (beginner → advanced)
        - Note any dependencies
        - Keep each subtask completable in ~1 session
        Output a numbered list.
        """,
        expected_output="A numbered, ordered list of subtasks with brief descriptions.",
        agent=planner
    )

def execution_task(goal: str, plan_task: Task) -> Task:
    days = parse_days(goal, default=7)
    dates = date_list(days)
    return Task(
        description=f"""
        Build a complete day-by-day schedule for: "{goal}"
        Use tools:
        - Web Search (Serper): find key topics/resources (e.g., 'RHCSA syllabus', 'RHCSA labs', 'SELinux basics')
        Instructions:
        - Use these dates (one subtask per day when possible):
{dates}
        - Estimate time: theory 1–2h, hands-on 3–4h, review 1h
        - Include at least 1 actionable tip and 1–2 useful links per day when relevant
        Output a clear list: Day, Date, Topics, Estimated time, Tip, Links.
        """,
        expected_output="A day-by-day schedule with date, topics, estimates, tips, and links.",
        agent=executor,
        context=[plan_task]  # Executor receives the Planner's output
    )

# 7) Orchestration
def run_crew(goal: str):
    p_task = planning_task(goal)
    e_task = execution_task(goal, p_task)
    crew = Crew(
        agents=[planner, executor],
        tasks=[p_task, e_task],
        process=Process.sequential,
        verbose=1
    )
    print(f"\n🎯 Goal: {goal}\n")
    result = crew.kickoff()
    print("\n✅ Final Result:\n")
    print(result)
    return result

# 8) Example
result = run_crew("Plan a study schedule for RHCSA in 10 days")

from IPython.display import Markdown

# CrewAI returns CrewOutput — access its raw text
Markdown(result.raw)